[package]
name = "uwunya"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
askama = { version = "0.12", features = ["with-axum"] }
askama_axum = "0.4"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }